class DisplayTextNormalizer {
  const DisplayTextNormalizer._();

  static final Map<String, String> _traditionalToSimplified =
      Map<String, String>.fromEntries(<MapEntry<String, String>>[
    MapEntry('萬', '万'),
    MapEntry('與', '与'),
    MapEntry('專', '专'),
    MapEntry('業', '业'),
    MapEntry('東', '东'),
    MapEntry('絲', '丝'),
    MapEntry('兩', '两'),
    MapEntry('個', '个'),
    MapEntry('為', '为'),
    MapEntry('麼', '么'),
    MapEntry('樂', '乐'),
    MapEntry('書', '书'),
    MapEntry('亂', '乱'),
    MapEntry('乾', '干'),
    MapEntry('了', '了'),
    MapEntry('亞', '亚'),
    MapEntry('產', '产'),
    MapEntry('親', '亲'),
    MapEntry('人體', '人体'),
    MapEntry('優', '优'),
    MapEntry('會', '会'),
    MapEntry('傘', '伞'),
    MapEntry('傳', '传'),
    MapEntry('傷', '伤'),
    MapEntry('倫', '伦'),
    MapEntry('來', '来'),
    MapEntry('係', '系'),
    MapEntry('個', '个'),
    MapEntry('們', '们'),
    MapEntry('價', '价'),
    MapEntry('兒', '儿'),
    MapEntry('內', '内'),
    MapEntry('兩', '两'),
    MapEntry('關', '关'),
    MapEntry('興', '兴'),
    MapEntry('冊', '册'),
    MapEntry('寫', '写'),
    MapEntry('軍', '军'),
    MapEntry('農', '农'),
    MapEntry('凍', '冻'),
    MapEntry('別', '别'),
    MapEntry('劃', '划'),
    MapEntry('劇', '剧'),
    MapEntry('動', '动'),
    MapEntry('務', '务'),
    MapEntry('勁', '劲'),
    MapEntry('勵', '励'),
    MapEntry('勸', '劝'),
    MapEntry('勢', '势'),
    MapEntry('區', '区'),
    MapEntry('協', '协'),
    MapEntry('單', '单'),
    MapEntry('卻', '却'),
    MapEntry('參', '参'),
    MapEntry('雙', '双'),
    MapEntry('發', '发'),
    MapEntry('變', '变'),
    MapEntry('叢', '丛'),
    MapEntry('葉', '叶'),
    MapEntry('號', '号'),
    MapEntry('後', '后'),
    MapEntry('嗎', '吗'),
    MapEntry('員', '员'),
    MapEntry('問', '问'),
    MapEntry('啟', '启'),
    MapEntry('嗎', '吗'),
    MapEntry('國', '国'),
    MapEntry('圖', '图'),
    MapEntry('團', '团'),
    MapEntry('圓', '圆'),
    MapEntry('場', '场'),
    MapEntry('聲', '声'),
    MapEntry('壓', '压'),
    MapEntry('處', '处'),
    MapEntry('備', '备'),
    MapEntry('夠', '够'),
    MapEntry('夢', '梦'),
    MapEntry('夥', '伙'),
    MapEntry('頭', '头'),
    MapEntry('奪', '夺'),
    MapEntry('奮', '奋'),
    MapEntry('婦', '妇'),
    MapEntry('學', '学'),
    MapEntry('實', '实'),
    MapEntry('對', '对'),
    MapEntry('導', '导'),
    MapEntry('將', '将'),
    MapEntry('專', '专'),
    MapEntry('尋', '寻'),
    MapEntry('對', '对'),
    MapEntry('屆', '届'),
    MapEntry('屍', '尸'),
    MapEntry('屜', '屉'),
    MapEntry('屬', '属'),
    MapEntry('岡', '冈'),
    MapEntry('島', '岛'),
    MapEntry('峽', '峡'),
    MapEntry('崗', '岗'),
    MapEntry('幣', '币'),
    MapEntry('幫', '帮'),
    MapEntry('廣', '广'),
    MapEntry('庫', '库'),
    MapEntry('應', '应'),
    MapEntry('廠', '厂'),
    MapEntry('廳', '厅'),
    MapEntry('張', '张'),
    MapEntry('強', '强'),
    MapEntry('當', '当'),
    MapEntry('錄', '录'),
    MapEntry('徑', '径'),
    MapEntry('從', '从'),
    MapEntry('復', '复'),
    MapEntry('徵', '征'),
    MapEntry('後', '后'),
    MapEntry('徹', '彻'),
    MapEntry('恆', '恒'),
    MapEntry('恥', '耻'),
    MapEntry('愛', '爱'),
    MapEntry('慶', '庆'),
    MapEntry('憂', '忧'),
    MapEntry('應', '应'),
    MapEntry('戲', '戏'),
    MapEntry('戶', '户'),
    MapEntry('拋', '抛'),
    MapEntry('挾', '挟'),
    MapEntry('換', '换'),
    MapEntry('據', '据'),
    MapEntry('擁', '拥'),
    MapEntry('擇', '择'),
    MapEntry('擊', '击'),
    MapEntry('擋', '挡'),
    MapEntry('擾', '扰'),
    MapEntry('攝', '摄'),
    MapEntry('攤', '摊'),
    MapEntry('數', '数'),
    MapEntry('整', '整'),
    MapEntry('斂', '敛'),
    MapEntry('斷', '断'),
    MapEntry('於', '于'),
    MapEntry('無', '无'),
    MapEntry('時', '时'),
    MapEntry('晉', '晋'),
    MapEntry('暈', '晕'),
    MapEntry('暢', '畅'),
    MapEntry('曆', '历'),
    MapEntry('會', '会'),
    MapEntry('東', '东'),
    MapEntry('條', '条'),
    MapEntry('來', '来'),
    MapEntry('極', '极'),
    MapEntry('樣', '样'),
    MapEntry('歡', '欢'),
    MapEntry('歲', '岁'),
    MapEntry('歷', '历'),
    MapEntry('歸', '归'),
    MapEntry('氣', '气'),
    MapEntry('沒', '没'),
    MapEntry('決', '决'),
    MapEntry('況', '况'),
    MapEntry('沖', '冲'),
    MapEntry('潔', '洁'),
    MapEntry('測', '测'),
    MapEntry('灣', '湾'),
    MapEntry('無', '无'),
    MapEntry('煩', '烦'),
    MapEntry('熱', '热'),
    MapEntry('燈', '灯'),
    MapEntry('營', '营'),
    MapEntry('爐', '炉'),
    MapEntry('爭', '争'),
    MapEntry('為', '为'),
    MapEntry('爾', '尔'),
    MapEntry('牆', '墙'),
    MapEntry('獎', '奖'),
    MapEntry('獨', '独'),
    MapEntry('獸', '兽'),
    MapEntry('現', '现'),
    MapEntry('畫', '画'),
    MapEntry('當', '当'),
    MapEntry('發', '发'),
    MapEntry('盜', '盗'),
    MapEntry('盡', '尽'),
    MapEntry('監', '监'),
    MapEntry('盤', '盘'),
    MapEntry('眾', '众'),
    MapEntry('著', '着'),
    MapEntry('瞭', '了'),
    MapEntry('矚', '瞩'),
    MapEntry('礦', '矿'),
    MapEntry('祕', '秘'),
    MapEntry('種', '种'),
    MapEntry('稱', '称'),
    MapEntry('穩', '稳'),
    MapEntry('積', '积'),
    MapEntry('窩', '窝'),
    MapEntry('競', '竞'),
    MapEntry('筆', '笔'),
    MapEntry('築', '筑'),
    MapEntry('簡', '简'),
    MapEntry('簽', '签'),
    MapEntry('級', '级'),
    MapEntry('紅', '红'),
    MapEntry('約', '约'),
    MapEntry('紀', '纪'),
    MapEntry('純', '纯'),
    MapEntry('納', '纳'),
    MapEntry('紙', '纸'),
    MapEntry('級', '级'),
    MapEntry('紋', '纹'),
    MapEntry('終', '终'),
    MapEntry('經', '经'),
    MapEntry('結', '结'),
    MapEntry('給', '给'),
    MapEntry('統', '统'),
    MapEntry('維', '维'),
    MapEntry('網', '网'),
    MapEntry('羅', '罗'),
    MapEntry('罷', '罢'),
    MapEntry('聖', '圣'),
    MapEntry('聞', '闻'),
    MapEntry('聯', '联'),
    MapEntry('聲', '声'),
    MapEntry('聰', '聪'),
    MapEntry('肅', '肃'),
    MapEntry('脅', '胁'),
    MapEntry('腦', '脑'),
    MapEntry('臉', '脸'),
    MapEntry('臺', '台'),
    MapEntry('與', '与'),
    MapEntry('興', '兴'),
    MapEntry('舉', '举'),
    MapEntry('艦', '舰'),
    MapEntry('艱', '艰'),
    MapEntry('藝', '艺'),
    MapEntry('萬', '万'),
    MapEntry('葉', '叶'),
    MapEntry('著', '着'),
    MapEntry('蒼', '苍'),
    MapEntry('蔥', '葱'),
    MapEntry('蕭', '萧'),
    MapEntry('號', '号'),
    MapEntry('虧', '亏'),
    MapEntry('補', '补'),
    MapEntry('裝', '装'),
    MapEntry('複', '复'),
    MapEntry('襲', '袭'),
    MapEntry('見', '见'),
    MapEntry('視', '视'),
    MapEntry('覺', '觉'),
    MapEntry('覽', '览'),
    MapEntry('觀', '观'),
    MapEntry('觸', '触'),
    MapEntry('訂', '订'),
    MapEntry('計', '计'),
    MapEntry('訊', '讯'),
    MapEntry('討', '讨'),
    MapEntry('記', '记'),
    MapEntry('訓', '训'),
    MapEntry('設', '设'),
    MapEntry('訪', '访'),
    MapEntry('證', '证'),
    MapEntry('譯', '译'),
    MapEntry('讓', '让'),
    MapEntry('豐', '丰'),
    MapEntry('貓', '猫'),
    MapEntry('責', '责'),
    MapEntry('貴', '贵'),
    MapEntry('買', '买'),
    MapEntry('費', '费'),
    MapEntry('賀', '贺'),
    MapEntry('資', '资'),
    MapEntry('賽', '赛'),
    MapEntry('贊', '赞'),
    MapEntry('贏', '赢'),
    MapEntry('趕', '赶'),
    MapEntry('車', '车'),
    MapEntry('轉', '转'),
    MapEntry('輕', '轻'),
    MapEntry('輸', '输'),
    MapEntry('這', '这'),
    MapEntry('連', '连'),
    MapEntry('進', '进'),
    MapEntry('遊', '游'),
    MapEntry('過', '过'),
    MapEntry('還', '还'),
    MapEntry('週', '周'),
    MapEntry('運', '运'),
    MapEntry('過', '过'),
    MapEntry('達', '达'),
    MapEntry('違', '违'),
    MapEntry('選', '选'),
    MapEntry('遞', '递'),
    MapEntry('遙', '遥'),
    MapEntry('遺', '遗'),
    MapEntry('醫', '医'),
    MapEntry('醬', '酱'),
    MapEntry('釋', '释'),
    MapEntry('重', '重'),
    MapEntry('野', '野'),
    MapEntry('錄', '录'),
    MapEntry('鐘', '钟'),
    MapEntry('鐵', '铁'),
    MapEntry('長', '长'),
    MapEntry('門', '门'),
    MapEntry('閃', '闪'),
    MapEntry('閉', '闭'),
    MapEntry('開', '开'),
    MapEntry('間', '间'),
    MapEntry('關', '关'),
    MapEntry('隊', '队'),
    MapEntry('階', '阶'),
    MapEntry('際', '际'),
    MapEntry('雜', '杂'),
    MapEntry('雞', '鸡'),
    MapEntry('離', '离'),
    MapEntry('難', '难'),
    MapEntry('電', '电'),
    MapEntry('雲', '云'),
    MapEntry('靈', '灵'),
    MapEntry('靜', '静'),
    MapEntry('頂', '顶'),
    MapEntry('頁', '页'),
    MapEntry('項', '项'),
    MapEntry('順', '顺'),
    MapEntry('頓', '顿'),
    MapEntry('預', '预'),
    MapEntry('領', '领'),
    MapEntry('頭', '头'),
    MapEntry('頻', '频'),
    MapEntry('顯', '显'),
    MapEntry('類', '类'),
    MapEntry('風', '风'),
    MapEntry('飛', '飞'),
    MapEntry('飲', '饮'),
    MapEntry('餘', '余'),
    MapEntry('館', '馆'),
    MapEntry('馬', '马'),
    MapEntry('驅', '驱'),
    MapEntry('驗', '验'),
    MapEntry('鬥', '斗'),
    MapEntry('魚', '鱼'),
    MapEntry('麗', '丽'),
    MapEntry('點', '点'),
    MapEntry('龍', '龙'),
    MapEntry('溫', '温'),
  ]);

  static String normalize(String? raw) {
    if (raw == null || raw.isEmpty) {
      return '';
    }
    var text = _stripMalformedUtf16(raw);
    for (var index = 0; index < 2; index += 1) {
      text = text
          .replaceAll('&amp;nbsp;', ' ')
          .replaceAll('&nbsp;', ' ')
          .replaceAll('&#160;', ' ')
          .replaceAll('&amp;', '&')
          .replaceAll('&lt;', '<')
          .replaceAll('&gt;', '>')
          .replaceAll('&quot;', '"')
          .replaceAll('&#39;', "'");
    }
    text = text
        .replaceAll(RegExp(r'<br\s*/?>', caseSensitive: false), ' ')
        .replaceAll(RegExp(r'</p\s*>', caseSensitive: false), ' ')
        .replaceAll(RegExp(r'<[^>]+>'), ' ')
        .replaceAll(' ', ' ')
        .replaceAll('​', '')
        .replaceAll('﻿', '');
    final buffer = StringBuffer();
    for (final rune in text.runes) {
      final character = String.fromCharCode(rune);
      buffer.write(_traditionalToSimplified[character] ?? character);
    }
    return buffer.toString().replaceAll(RegExp(r'\s+'), ' ').trim();
  }

  static String _stripMalformedUtf16(String raw) {
    final units = raw.codeUnits;
    final buffer = StringBuffer();
    var index = 0;
    while (index < units.length) {
      final unit = units[index];
      if (unit >= 0xD800 && unit <= 0xDBFF) {
        if (index + 1 < units.length) {
          final next = units[index + 1];
          if (next >= 0xDC00 && next <= 0xDFFF) {
            buffer
              ..writeCharCode(unit)
              ..writeCharCode(next);
            index += 2;
            continue;
          }
        }
        index += 1;
        continue;
      }
      if (unit >= 0xDC00 && unit <= 0xDFFF) {
        index += 1;
        continue;
      }
      buffer.writeCharCode(unit);
      index += 1;
    }
    return buffer.toString();
  }
}

String normalizeDisplayText(String? raw) {
  return DisplayTextNormalizer.normalize(raw);
}
